<#
.SYNOPSIS
    Register the daily AI-trader pipeline as a Windows Scheduled Task.

.DESCRIPTION
    Creates / updates a Scheduled Task named "AITrader-Daily" that runs
    `python -m scripts.run_daily` every day at the configured local time.
    The task runs as the current user (no admin required) and will wake
    the system if necessary, but skips gracefully on weekends (NSE is
    closed Sat/Sun -- the script itself short-circuits if it sees no
    fresh price bars, but this avoids the noise).

.PARAMETER TaskName
    Defaults to "AITrader-Daily". Pass a different name to register
    multiple variants (e.g. paper vs research).

.PARAMETER At
    Local time (HH:mm) to run the task. Defaults to 18:00 IST -- after
    NSE close (15:30) and after yfinance has its EOD bars.

.PARAMETER ProjectRoot
    Path to ai_trading_system/. Defaults to the script's parent's parent
    (so running `.\scripts\setup_windows_scheduler.ps1` from the repo
    root just works).

.PARAMETER Python
    Python executable. Defaults to .venv\Scripts\python.exe relative to
    ProjectRoot.

.PARAMETER DryRun
    Pass -DryRun to register a task that only renders the report (no
    email/WhatsApp send) -- handy for verifying scheduling without
    spamming your inbox.

.EXAMPLE
    PS> .\scripts\setup_windows_scheduler.ps1

.EXAMPLE
    PS> .\scripts\setup_windows_scheduler.ps1 -At 18:30 -DryRun

.NOTES
    Re-running the script overwrites the existing task with the same
    name (idempotent). To remove the task:
        Unregister-ScheduledTask -TaskName 'AITrader-Daily' -Confirm:$false

    Logs land in <ProjectRoot>\logs\app_YYYY-MM-DD.log per the loguru
    configuration. The Scheduled Task itself logs run history under
    Task Scheduler (Library) > AITrader-Daily.

    SECURITY: this script DOES NOT store passwords. Tasks run with
    "InteractiveToken" auth, meaning they only fire when you're logged
    in. For an always-on cloud VM, prefer cron / systemd-timer instead.
#>

[CmdletBinding()]
param(
    [string]$TaskName = "AITrader-Daily",
    [string]$At = "18:00",
    [string]$ProjectRoot = $(Resolve-Path (Join-Path $PSScriptRoot "..")),
    [string]$Python = "",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------

$ProjectRoot = (Resolve-Path $ProjectRoot).Path
if (-not (Test-Path -LiteralPath $ProjectRoot)) {
    throw "ProjectRoot '$ProjectRoot' does not exist."
}

if ([string]::IsNullOrWhiteSpace($Python)) {
    $Python = Join-Path $ProjectRoot ".venv\Scripts\python.exe"
}
if (-not (Test-Path -LiteralPath $Python)) {
    throw "Python '$Python' not found. Did you create the venv? See README.md Setup."
}

$Module = "scripts.run_daily"
$Args   = @("-m", $Module, "--print-summary")
if ($DryRun) { $Args += "--dry-run" }

Write-Host "Registering scheduled task '$TaskName'"
Write-Host "  ProjectRoot : $ProjectRoot"
Write-Host "  Python      : $Python"
Write-Host "  Run at      : $At  (local time)"
Write-Host "  Args        : $($Args -join ' ')"

# ---------------------------------------------------------------------------
# Build the task
# ---------------------------------------------------------------------------

# We use the *full* path to python.exe (no shell expansion required) and pass
# the ProjectRoot as the WorkingDirectory so relative paths in config/.env
# resolve correctly.
$action = New-ScheduledTaskAction `
    -Execute $Python `
    -Argument ($Args -join ' ') `
    -WorkingDirectory $ProjectRoot

# Daily at $At, weekdays only (NSE is shut Sat/Sun). DaysOfWeek requires the
# Weekly trigger; for daily-no-weekend we set Weekly + Mon..Fri.
$trigger = New-ScheduledTaskTrigger `
    -Weekly `
    -DaysOfWeek Monday,Tuesday,Wednesday,Thursday,Friday `
    -At ([datetime]::ParseExact($At, "HH:mm", $null))

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Hours 1) `
    -RestartCount 2 `
    -RestartInterval (New-TimeSpan -Minutes 5) `
    -MultipleInstances IgnoreNew

# Run as the current user, only when logged on (no stored creds).
$principal = New-ScheduledTaskPrincipal `
    -UserId (whoami) `
    -LogonType Interactive `
    -RunLevel Limited

$task = New-ScheduledTask `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description ("AI Trading System - daily pipeline (run_daily.py). " +
                  "Generated by setup_windows_scheduler.ps1 on $(Get-Date -Format 'yyyy-MM-dd').")

# ---------------------------------------------------------------------------
# Register (idempotent: -Force overwrites an existing task with same name)
# ---------------------------------------------------------------------------

Register-ScheduledTask -TaskName $TaskName -InputObject $task -Force | Out-Null

Write-Host ""
Write-Host "Task '$TaskName' registered." -ForegroundColor Green
Write-Host "Verify with:"
Write-Host "  Get-ScheduledTask -TaskName '$TaskName' | Format-List"
Write-Host "Run once on demand:"
Write-Host "  Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "View execution history:"
Write-Host "  Get-ScheduledTaskInfo -TaskName '$TaskName'"
Write-Host "Remove:"
Write-Host "  Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
